### ISSUE TITLE
Nice app 

### ISSUE THREAD

**Issue by konstantinakatmada** [fac26/week-10-12-TFB-Eric-gild#50]
- [x] looks great in all mobile devices 🚀 💯 
- [x] authentication went on smoothly 🏅 
- [x] (beautiful) responsive navbar is done and eagerly waiting for ⌛  pages 
- [x] the vendor form works the first time input is added to it, (I can see airtable utils but 
    maybe access to databases would allow us to see what is going on?)
- [x]  if I set all food items to 0 as a Vendor I still get the list of items back with a Currently Available heading
- [x]  Sign Out does not work at the moment
- [x]  the More Info buttons in the find-food page currently redirect to HomePage

**Comment by GalKJ** [comment]
Hey @konstantinakatmada 

Thanks for your comments, we've made issues and will pop them in our backlog
