### ISSUE TITLE
index page button hover

### ISSUE THREAD

**Issue by rockyrelay** [fac26/week-10-12-TFB-Eric-gild#51]
The styling works on the food page cards, but feels odd/is not very accessible on the index/landing page for the button to 'disappear' when the background is green. 
<img width="189" alt="image" src="https://user-images.githubusercontent.com/81175151/228606501-b038722a-5bc8-4e54-933d-3f54c4e3961d.png">
<img width="206" alt="image" src="https://user-images.githubusercontent.com/81175151/228606553-1316e7d9-320b-455f-99b5-e523625cdc99.png">

**Comment by LauraK0** [comment]
Good spot, we'll try and fix
